import { Router } from 'express';
import ExcelJS from 'exceljs';
import PDFDocument from 'pdfkit';
import { prisma } from '../../config/db.js';
import { authenticate } from '../../middlewares/auth.js';
import { asyncHandler } from '../../utils/asyncHandler.js';
const router=Router(); router.use(authenticate);
router.get('/assets.xlsx', asyncHandler(async (_,res)=>{const wb=new ExcelJS.Workbook();const ws=wb.addWorksheet('Aktivlar');ws.columns=['ID','Nomi','Inventar raqami','Holati'].map(h=>({header:h,key:h,width:25}));(await prisma.asset.findMany()).forEach(a=>ws.addRow({'ID':a.id,'Nomi':a.name,'Inventar raqami':a.inventoryNumber,'Holati':a.status}));res.setHeader('Content-Type','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');res.setHeader('Content-Disposition','attachment; filename=assets.xlsx');await wb.xlsx.write(res);res.end();}));
router.get('/assets.pdf', asyncHandler(async (_,res)=>{const doc=new PDFDocument();res.setHeader('Content-Type','application/pdf');res.setHeader('Content-Disposition','attachment; filename=assets.pdf');doc.pipe(res);doc.fontSize(18).text('Aktivlar hisoboti');for(const a of await prisma.asset.findMany()) doc.fontSize(10).text(`${a.id}. ${a.name} - ${a.inventoryNumber} - ${a.status}`);doc.end();}));
export default router;
