ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'SUPER_ADMIN';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'ORGANIZATION_ADMIN';

ALTER TABLE "User" ADD COLUMN "managedOrganizationId" INTEGER;

ALTER TABLE "User" ADD CONSTRAINT "User_managedOrganizationId_fkey"
FOREIGN KEY ("managedOrganizationId") REFERENCES "Organization"("id")
ON DELETE SET NULL ON UPDATE CASCADE;
