import { Router } from 'express';
import authRoutes from '../modules/auth/auth.routes.js';
import assetRoutes from '../modules/assets/assets.routes.js';
import userRoutes from '../modules/users/users.routes.js';
import departmentRoutes from '../modules/departments/departments.routes.js';
import transactionRoutes from '../modules/transactions/transactions.routes.js';
import maintenanceRoutes from '../modules/maintenance/maintenance.routes.js';
import dashboardRoutes from '../modules/dashboard/dashboard.routes.js';
import reportRoutes from '../modules/reports/reports.routes.js';
import auditRoutes from '../modules/audit/audit.routes.js';
const router = Router();
router.use('/auth', authRoutes);
router.use('/assets', assetRoutes);
router.use('/users', userRoutes);
router.use('/departments', departmentRoutes);
router.use('/transactions', transactionRoutes);
router.use('/maintenance', maintenanceRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/reports', reportRoutes);
router.use('/audit-logs', auditRoutes);
export default router;
