ALTER TYPE "DeliveryActStatus" ADD VALUE IF NOT EXISTS 'AWAITING_ACCEPTANCE';

ALTER TABLE "DeliveryAct"
ADD COLUMN "acceptedAt" TIMESTAMP(3),
ADD COLUMN "acceptedById" INTEGER;

ALTER TABLE "DeliveryAct"
ADD CONSTRAINT "DeliveryAct_acceptedById_fkey"
FOREIGN KEY ("acceptedById") REFERENCES "User"("id")
ON DELETE SET NULL ON UPDATE CASCADE;
